[distributed]
gpus_per_node = 8

[parallelism]
pp_size = 8
num_layers_per_virtual_pipeline_stage = 5

[model]
dim = 8192
n_layers = 80
n_heads = 64
n_kv_heads = 8
vocab_size = 128256
multiple_of = 4096
ffn_dim_multiplier = 1.3
norm_eps = 1e-5
rope_theta = 500000.0
swiglu = true
disable_bias_linear = true
untie_embeddings_and_output_weights = true
apply_layernorm_1p = true

[training]
micro_batch_size = 1
global_batch_size = 128
seq_length = 2048
max_position_embeddings = 8192
train_iters = 25
lr = 0.00015
min_lr = 0.00001
lr_decay_style = "cosine"
weight_decay = 0.1
clip_grad = 1.0
use_distributed_optimizer = false
log_interval = 1
eval_iters = 1
eval_interval = 10
save_interval = 1000
log_throughput = true

recompute_granularity = "full"

recompute_method="uniform"
recompute_num_layers=1

[precision]
dtype = "bf16"

[data]
use_mock_data = true
split = "90,5,5"
